
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-courses
owner: ucsb-cs156
repo_name: proj-courses
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-04","number":243,"title":"f25-04","url":"https://github.com/ucsb-cs156/proj-courses/pull/243"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-03","number":242,"title":"f25-03","url":"https://github.com/ucsb-cs156/proj-courses/pull/242"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-02","number":241,"title":"f25-02","url":"https://github.com/ucsb-cs156/proj-courses/pull/241"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"f25-01","number":240,"title":"f25-01","url":"https://github.com/ucsb-cs156/proj-courses/pull/240"}]
