# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: "10-backend-unit: Java Unit tests"

on:
  workflow_dispatch:
  pull_request:
    paths: [src/**, pom.xml, lombok.config, .github/workflows/10-backend-unit.yml]
  push:
    branches: [ main ]
    paths: [src/**, pom.xml, lombok.config, .github/workflows/10-backend-unit.yml]


jobs:
  call-workflow-passing-data:
    uses: ucsb-cs156/workflows/.github/workflows/10-backend-unit.yml@main
    secrets: 
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    with:
      JAVA_DISTRIBUTION:  ${{ vars.JAVA_DISTRIBUTION || 'temurin' }} 

