# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: "13-backend-incremental-pitest: Java Mutation Testing (Pitest)"

on:
  workflow_dispatch:
  pull_request:
    paths: [src/**, pom.xml, lombok.config, .github/workflows/13-backend-incremental-pitest.yml]
  push:
    branches: [ main ]
    paths: [src/**, pom.xml, lombok.config, .github/workflows/13-backend-incremental-pitest.yml]

jobs:
  call-backend-incremental-pitest:
    uses: ucsb-cs156/workflows/.github/workflows/13-backend-incremental-pitest.yml@main
    with:
      JAVA_DISTRIBUTION: ${{ vars.JAVA_DISTRIBUTION || 'temurin' }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
